### ISSUE TITLE
cmake error during compile

### ISSUE THREAD

**Issue by johnlees** [santeripuranen/SuperDCA#2]
Hi,

I am trying to compile from source (using cmake 3.4.1 and gcc 4.9.1) and get the following error when running `cmake -DCMAKE_BUILD_TYPE=Release ..` from a directory `SuperDCA/build`:
```
CMake Error at externals/CMakeLists.txt:22 (string):
  string sub-command REPLACE requires at least four arguments.
...
-- Configuring incomplete, errors occurred!
```
I've attached [CMakeOutput.log.txt](https://github.com/santeripuranen/SuperDCA/files/1296329/CMakeOutput.log.txt) here

**Comment by vaofford** [comment]
Following this process we also get the same error using cmake 3.9.4, Eigen 3.3.4 and gcc versions 4.9.2 and 6.2.0 (log attached).

[CMakeOutput.log](https://github.com/santeripuranen/SuperDCA/files/1461062/CMakeOutput.log)

**Comment by YangChaoCN** [comment]
I also got the same error in CMakeLists.txt line  22, is the problem solved?

**Comment by santeripuranen** [comment]
The error is fixed now and was due to sloppy guarding against empty strings in externals/CMakeLists.txt. In this case the error was triggered by not having the (shell) environment variable CMAKE_MODULE_PATH defined on the host system. CMAKE_MODULE_PATH is not compulsory, but can be used to help CMake find dependencies that are installed in non-standard places on the host.

My apologies for the very slow response here.
